// src/routes/+page.svelte
<script lang="ts">
	import Trophies from '$lib/components/Trophies.svelte';
	import NextMatch from '$lib/components/NextMatch.svelte';
	import StatsTable from '$lib/components/StatsTable.svelte';
	import FloatingChat from '$lib/components/FloatingChat.svelte';

	let { data } = $props();

	let leaguesData = $derived(data.snapshot?.leaguesData ?? []);
	let nextMatchData = $derived(data.snapshot?.nextMatchData ?? undefined);
</script>

<svelte:head>
	<title>הכפית</title>
	<meta name="description" content="דף הבית של משפחת הכפית" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://hakapit.online/" />
	<meta property="og:title" content="הכפית" />
	<meta property="og:description" content="דף הבית של משפחת הכפית" />
	<meta property="og:image" content="https://hakapit.online/icon-512x512.png" />
</svelte:head>

<section class="lg:about lg:py-0 flex flex-col items-center justify-center h-full py-4 text-center">
	<div class="flex flex-col w-full gap-10">
		<Trophies />

		<NextMatch {nextMatchData} />

		<StatsTable {leaguesData} />
	</div>
	<FloatingChat />
</section>

// src/routes/index.tsx
import { convexQuery } from "@convex-dev/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { api } from "convex/_generated/api";
import { FloatingChat } from "~/app/components/chat/FloatingChat";
import { LatestEpisode } from "~/app/components/convex/LatestEpisode";
import { RecentTransfers } from "~/app/components/convex/RecentTransfers";
import { NextMatchOverview } from "~/app/components/next-match";
import { StatsTable } from "~/app/components/stats/Stats";
import { Trophies } from "~/app/components/stats/Trophies";
import { getLeague, getNextMatchData, getTeam } from "~/app/providers/soccer-api";
import type { League } from "~/app/providers/soccer-api/types/league";

export const Route = createFileRoute("/")({
	component: Home,
	loader: async (opts) => {
		const team = await getTeam();
		if (!team?.runningCompetitions) {
			return { leaguesData: [] as Array<{ leagueId: string; league: League }> };
		}

		const leagueIds = Array.from(new Set(team.runningCompetitions.map((c) => c.code).filter(Boolean)));
		const leagues = await Promise.all(leagueIds.map((leagueId) => getLeague({ data: leagueId })));
		const pairs = leagues
			.map((league, index) => {
				const leagueId = leagueIds[index];
				if (!league || !leagueId) return null;
				return { leagueId, league };
			})
			.filter(Boolean) as Array<{ leagueId: string; league: League }>;

		const nextMatchData = await getNextMatchData();
		await opts.context.queryClient.prefetchQuery({
			...convexQuery(api.football.getAllTransfers, {}),
		});
		return { leaguesData: pairs, nextMatchData };
	},
	head: () => ({
		title: "הכפית",

		meta: [
			{
				name: "description",
				content: "דף הבית של משפחת הכפית",
			},
			{
				property: "viewport",
				content: "width=device-width, initial-scale=1.0",
			},
			{
				property: "theme-color",
				content: "var(--color-primary)",
			},
			{
				property: "color-scheme",
				content: "dark light",
			},
			{ property: "og:type", content: "website" },
			{ property: "og:url", content: "https://hakapit.online/" },
			{ property: "og:title", content: "הכפית" },
			{ property: "og:description", content: "דף הבית של משפחת הכפית" },
			{ property: "og:image", content: "https://hakapit.online/icon-512x512.png" },
			{ name: "twitter:card", content: "summary_large_image" },
			{ name: "twitter:title", content: "הכפית" },
			{ name: "twitter:description", content: "דף הבית של משפחת הכפית" },
			{ name: "twitter:image", content: "https://hakapit.online/icon-512x512.png" },
			{ name: "twitter:url", content: "https://hakapit.online/" },
		],
	}),
});

function Home() {
	const { leaguesData, nextMatchData } = Route.useLoaderData();

	return (
		<section className="lg:about lg:py-0 flex flex-col items-center justify-center h-full py-4 text-center">
			<div className="flex flex-col w-full gap-10">
				<Trophies />
				<div className="flex flex-wrap justify-center">
					<LatestEpisode />
				</div>
				<div className="flex flex-wrap justify-center">
					<RecentTransfers />
				</div>
				<NextMatchOverview nextMatchData={nextMatchData} />
				<StatsTable leaguesData={leaguesData} />
			</div>
			<FloatingChat />
		</section>
	);
}
