// src/lib/components/TeamAvatar.svelte
<script lang="ts">
	import type { Team } from '$lib/types/soccer';

	let {
		team,
		iconPosition = 'before',
		color,
		hoverable = false
	}: {
		team: Team;
		iconPosition?: 'before' | 'after';
		color?: string;
		hoverable?: boolean;
	} = $props();
</script>

{#if team.id}
	{#if hoverable}
		<div
			class="size-[25px] rounded-full overflow-hidden"
			title={team.name}
		>
			<img
				src={team.crest}
				width="25"
				height="25"
				loading="lazy"
				alt={team.shortName || 'TL'}
			/>
		</div>
	{:else}
		<div
			class="flex items-center gap-3 {iconPosition === 'after'
				? 'justify-end'
				: 'justify-start'}"
		>
			{#if iconPosition === 'after'}
				<div class="text-sm md:text-lg text-amber-100" style:color>{team.name}</div>
			{/if}
			<div class="size-[25px] rounded-full overflow-hidden">
				<img
					src={team.crest}
					width="25"
					height="25"
					loading="lazy"
					alt={team.shortName || 'TL'}
				/>
			</div>
			{#if iconPosition === 'before'}
				<div class="text-sm md:text-lg text-amber-100" style:color>{team.name}</div>
			{/if}
		</div>
	{/if}
{/if}

// src/features/football/team-avatar.tsx
import { Image } from "@unpic/react";

import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "~/lib/ui/tooltip";

import type { Team } from "~/server/soccer-api/types/league";

export default function TeamNameAndAvatar({
  team,
  iconPosition = "before",
  color,
  hoverable = false,
}: {
  team: Team;
  iconPosition?: "before" | "after";
  color?: string;
  hoverable?: boolean;
}) {
  const { id: teamId, name: teamName, shortName: teamShortName, crest } = team;
  if (!teamId) {
    return null;
  }

  const teamNameComponent = (
    <div className="text-sm md:text-lg text-amber-100" style={{ color }}>
      {teamName}
    </div>
  );

  const teamCrest = (
    <div className="size-6.25 rounded-full overflow-hidden" style={{ width: 25, height: 25 }}>
      <Image src={crest} width={25} height={25} loading="lazy" alt={teamShortName || "TL"} />
    </div>
  );

  if (hoverable) {
    return (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger>{teamCrest}</TooltipTrigger>
          <TooltipContent side="bottom" className="rounded-xl bg-primary border-accent text-accent">
            <div>{teamName}</div>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  }

  return (
    <div className={`flex items-center gap-3 ${iconPosition === "after" ? "justify-end" : "justify-start"}`}>
      {iconPosition === "after" && teamNameComponent}
      {teamCrest}
      {iconPosition === "before" && teamNameComponent}
    </div>
  );
}
