// src/lib/components/EpisodeCard.svelte
<script lang="ts">
	import { getContext } from 'svelte';
	import { toDateString, removeIframes } from '$lib/utils';
	import type { Episode, EpisodeWithPodcast } from '$lib/types/podcast';

	let { episode }: { episode: EpisodeWithPodcast } = $props();

	const player = getContext<{
		currentlyPlaying: Episode | undefined;
		isPlaying: boolean;
		setCurrentlyPlaying: (ep?: Episode) => void;
	}>('player');

	let isoDate = $derived(
		toDateString(episode?.publishedAt ? new Date(episode.publishedAt) : null)
	);
	let podcast = $derived(episode?.podcast?.name || 'hakapit');
	let episodeNumber = $derived(episode?.episodeNumber);
	let isCurrentlyPlaying = $derived(
		player?.isPlaying && player?.currentlyPlaying?.guid === episode?.guid
	);
</script>

<div
	class="episode-card relative max-w-xl max-h-[450px] rounded-3xl overflow-hidden flex flex-col font-sans"
>
	{#if episode?.imageUrl}
		<div class="absolute inset-0 overflow-hidden rounded-3xl z-0">
			<img
				src={episode.imageUrl}
				alt="episode"
				loading="eager"
				class="min-h-full w-full brightness-[0.4] object-cover object-top blur-[2px]"
			/>
		</div>
	{/if}
	<div class="z-10 p-4">
		<h3 class="text-accent font-semibold">
			<a href="/{podcast}/episodes/{episodeNumber}">
				{episode?.title}
			</a>
		</h3>
		<p class="text-gray-400 text-sm">{isoDate}</p>
	</div>
	<div class="flex-1 min-h-0 text-paragraph z-10 overflow-hidden p-4 pt-0">
		{#if episode?.htmlDescription}
			<div class="card-content">
				{@html removeIframes(episode.htmlDescription)}
			</div>
		{/if}
	</div>
	<div class="mt-auto p-4 z-10">
		{#if player}
			<button
				disabled={isCurrentlyPlaying}
				class="w-full px-4 py-2 rounded-lg bg-primary text-accent border border-accent/20 hover:bg-primary/80 transition disabled:opacity-50 disabled:cursor-not-allowed"
				onclick={() => player.setCurrentlyPlaying(episode)}
			>
				{isCurrentlyPlaying ? 'מנגן כרגע' : 'נגן פרק'}
			</button>
		{:else}
			<audio class="audio" controls src={episode?.audioUrl}>
				<track kind="captions" />
			</audio>
		{/if}
	</div>
</div>

// app/components/rss/EpisodeCard.tsx
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import { PlayIcon } from "@radix-ui/react-icons";
import { Link } from "@remix-run/react";
import { usePlayer } from "~/components/player/provider";
import { Episode } from "~/db/types";
import { toDateString } from "~/hooks";
export function SkeletonCard({ className }: React.HTMLAttributes<HTMLDivElement>) {
	return (
		<Card className={cn("episode-card h-full w-full max-w-xl rounded-3xl", className)}>
			<CardHeader>
				<CardTitle>
					<Skeleton className="w-64 h-6 rounded-full bg-primary-opaque" />
				</CardTitle>
				<CardDescription>
					<Skeleton className="w-32 h-4 rounded-full bg-primary-opaque" />
				</CardDescription>
			</CardHeader>
			<CardContent>
				<Skeleton className="w-full h-32 rounded-2xl bg-primary-opaque" />
			</CardContent>
		</Card>
	);
}

export function EpisodeCard({
	episode,
	className,
	contentClassName,
}: {
	episode?: Episode;
	contentClassName?: React.HTMLAttributes<HTMLDivElement>["className"];
} & React.HTMLAttributes<HTMLDivElement>) {
	const isoDate = toDateString(episode?.publishedAt);
	const playerProps = usePlayer();
	console.log(episode);

	return (
		<Card className={cn("episode-card relative max-w-xl rounded-3xl overflow-hidden", className)}>
			{episode?.imageUrl && (
				<img
					src={episode?.imageUrl}
					alt="episode"
					placeholder="blur"
					className="absolute object-cover object-top -z-10 rounded-3xl brightness-40 filter"
				/>
			)}
			<CardHeader>
				<CardTitle className="text-accent">
					<Link to={`/${episode?.podcast?.name}/episodes/${episode?.episodeNumber}`}>{episode?.title}</Link>
				</CardTitle>
				<CardDescription className="text-muted">{isoDate}</CardDescription>
			</CardHeader>
			<CardContent className={cn("flex-1 text-paragraph", contentClassName)}>
				{episode?.htmlDescription && (
					<div
						className="card-content"
						// biome-ignore lint: noDangerouslySetInnerHtml
						dangerouslySetInnerHTML={{
							__html: episode?.htmlDescription,
						}}
					/>
				)}
			</CardContent>
			<CardFooter>
				{playerProps ? (
					<Button
						disabled={playerProps.currentlyPlaying?.guid === episode?.guid}
						className="w-full"
						onClick={() => playerProps.setCurrentlyPlaying(episode)}
					>
						{playerProps.currentlyPlaying?.guid === episode?.guid ? (
							<>מנגן כרגע</>
						) : (
							<>
								נגן פרק <PlayIcon className="ms-4" />
							</>
						)}
					</Button>
				) : (
					<audio className="audio" controls src={episode?.audioUrl}>
						<track kind="captions" />
					</audio>
				)}
			</CardFooter>
		</Card>
	);
}
