// src/lib/components/EpisodeCard.svelte
<script lang="ts">
	import { getContext } from 'svelte';
	import { toDateString, removeIframes } from '$lib/utils';
	import type { Episode, EpisodeWithPodcast } from '$lib/types/podcast';

	let { episode }: { episode: EpisodeWithPodcast } = $props();

	const player = getContext<{
		currentlyPlaying: Episode | undefined;
		isPlaying: boolean;
		setCurrentlyPlaying: (ep?: Episode) => void;
	}>('player');

	let isoDate = $derived(
		toDateString(episode?.publishedAt ? new Date(episode.publishedAt) : null)
	);
	let podcast = $derived(episode?.podcast?.name || 'hakapit');
	let episodeNumber = $derived(episode?.episodeNumber);
	let isCurrentlyPlaying = $derived(
		player?.isPlaying && player?.currentlyPlaying?.guid === episode?.guid
	);
</script>

<div
	class="episode-card relative max-w-xl max-h-[450px] rounded-3xl overflow-hidden flex flex-col font-sans"
>
	{#if episode?.imageUrl}
		<div class="absolute inset-0 overflow-hidden rounded-3xl z-0">
			<img
				src={episode.imageUrl}
				alt="episode"
				loading="eager"
				class="min-h-full w-full brightness-[0.4] object-cover object-top blur-[2px]"
			/>
		</div>
	{/if}
	<div class="z-10 p-4">
		<h3 class="text-accent font-semibold">
			<a href="/{podcast}/episodes/{episodeNumber}">
				{episode?.title}
			</a>
		</h3>
		<p class="text-gray-400 text-sm">{isoDate}</p>
	</div>
	<div class="flex-1 min-h-0 text-paragraph z-10 overflow-hidden p-4 pt-0">
		{#if episode?.htmlDescription}
			<div class="card-content">
				{@html removeIframes(episode.htmlDescription)}
			</div>
		{/if}
	</div>
	<div class="mt-auto p-4 z-10">
		{#if player}
			<button
				disabled={isCurrentlyPlaying}
				class="w-full px-4 py-2 rounded-lg bg-primary text-accent border border-accent/20 hover:bg-primary/80 transition disabled:opacity-50 disabled:cursor-not-allowed"
				onclick={() => player.setCurrentlyPlaying(episode)}
			>
				{isCurrentlyPlaying ? 'מנגן כרגע' : 'נגן פרק'}
			</button>
		{:else}
			<audio class="audio" controls src={episode?.audioUrl}>
				<track kind="captions" />
			</audio>
		{/if}
	</div>
</div>

// src/app/components/EpisodeCard.tsx
import { Link } from "@tanstack/react-router";
import { Image } from "@unpic/react";

import { Button } from "~/@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "~/@/components/ui/card";
import { cn } from "~/@/lib/utils";
import { PlayButton } from "~/app/components/PlayButton";
import { heebo } from "~/app/fonts";
import { usePlayer } from "~/app/layouts/Player/provider";
import { type EpisodeWithPodcast, toDateString } from "~/app/utils";

function removeIframes(content: string): string {
  if (!content) return content;

  return content.replace(/<iframe[^>]*>[\s\S]*?<\/iframe>/gi, "");
}

export function LastEpisodeCardPreview({ episode }: { episode: EpisodeWithPodcast }) {
  const isoDate = toDateString(episode?.publishedAt ? new Date(episode.publishedAt) : null);
  const playerProps = usePlayer();
  const podcast = episode?.podcast?.name || "hakapit";
  const episodeNumber = episode?.episodeNumber;

  return (
    <div className="flex items-center justify-center w-full gap-4 py-4">
      {playerProps && (
        <Button
          className="size-10 md:size-14 lg:size-20 md:rounded-full relative p-3 overflow-hidden"
          onClick={() => playerProps.setCurrentlyPlaying(episode)}
        >
          {episode?.imageUrl && (
            <div className="absolute inset-0 overflow-hidden z-0">
              <Image
                src={episode?.imageUrl}
                alt="episode"
                sizes="(min-width: 768px) 56px, 80px"
                className="min-h-full w-auto brightness-40 filter object-cover object-top"
                layout="fullWidth"
              />
            </div>
          )}
          <PlayButton episode={episode} size="md" />
        </Button>
      )}
      <div className="text-accent flex flex-col items-start">
        <Link
          preload="intent"
          className="text-base md:text-lg lg:text-xl"
          to="/$podcast/episodes/$id"
          params={{ podcast, id: String(episodeNumber) }}
        >
          {episode?.title}
        </Link>
        <div className="text-muted flex items-start gap-3 text-sm">
          <div className="">{isoDate}</div>
        </div>
      </div>
    </div>
  );
}

export function EpisodeCard({
  episode,
  className,
  contentClassName,
}: {
  episode?: EpisodeWithPodcast;
  contentClassName?: React.HTMLAttributes<HTMLDivElement>["className"];
} & React.HTMLAttributes<HTMLDivElement>) {
  const isoDate = toDateString(episode?.publishedAt ? new Date(episode.publishedAt) : null);
  const playerProps = usePlayer();
  const podcast = episode?.podcast?.name || "hakapit";
  const episodeNumber = episode?.episodeNumber;
  const viewTransitionKey = episode?.guid ? String(episode.guid) : episodeNumber != null ? String(episodeNumber) : "";

  return (
    <Card
      className={cn(
        "episode-card relative max-w-xl max-h-[450px] rounded-3xl overflow-hidden flex flex-col",
        className,
        heebo.className,
      )}
    >
      {episode?.imageUrl && (
        <div className="absolute inset-0 overflow-hidden rounded-3xl z-0">
          <Image
            src={episode?.imageUrl}
            alt="episode"
            loading="eager"
            sizes="576px"
            className="min-h-full w-auto brightness-40 filter blur-xs object-cover object-top"
            layout="fullWidth"
          />
        </div>
      )}
      <CardHeader className="z-10">
        <CardTitle className="text-accent">
          <Link
            to="/$podcast/episodes/$id"
            params={{ podcast, id: String(episodeNumber) }}
            style={viewTransitionKey ? { viewTransitionName: `episode-title-${viewTransitionKey}` } : undefined}
          >
            {episode?.title}
          </Link>
        </CardTitle>
        <CardDescription className="text-muted">{isoDate}</CardDescription>
      </CardHeader>
      <CardContent
        style={viewTransitionKey ? { viewTransitionName: `episode-content-${viewTransitionKey}` } : undefined}
        className={cn("flex-1 min-h-0 text-paragraph z-10 overflow-hidden", contentClassName)}
      >
        {episode?.htmlDescription && (
          <div
            className="card-content"
            dangerouslySetInnerHTML={{
              __html: removeIframes(episode?.htmlDescription),
            }}
          />
        )}
      </CardContent>
      <CardFooter className="mt-auto">
        {playerProps ? (
          <Button
            disabled={playerProps.currentlyPlaying?.guid === episode?.guid}
            className="z-10 w-full"
            onClick={() => playerProps.setCurrentlyPlaying(episode)}
          >
            <div className="flex items-center justify-center gap-2">
              {episode && <PlayButton episode={episode} size="sm" />}
              {playerProps.currentlyPlaying?.guid === episode?.guid ? "מנגן כרגע" : "נגן פרק"}
            </div>
          </Button>
        ) : (
          <audio className="audio" controls src={episode?.audioUrl}>
            <track kind="captions" />
          </audio>
        )}
      </CardFooter>
    </Card>
  );
}
