// app/components/chat/FloatingChat.tsx
"use client";

import { useChat } from "@ai-sdk/react";
import { CornerDownLeft, X } from "lucide-react";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Button } from "@/components/ui/button";
import {
	Drawer,
	DrawerClose,
	DrawerContent,
	DrawerDescription,
	DrawerHeader,
	DrawerTitle,
	DrawerTrigger,
} from "@/components/ui/drawer";
import { Textarea } from "@/components/ui/textarea";
import { useIsDesktop } from "@/lib/use-is-desktop";
import { getDirectionFromText } from "~/utils/text-direction";

export function FloatingChat() {
	const { messages, input, setInput, status, append } = useChat();
	const contentRef = useRef<HTMLDivElement>(null);
	const inputDir = getDirectionFromText(input);
	const isDesktop = useIsDesktop();
	const [sendError, setSendError] = useState<string | null>(null);

	// The most recent user message id (used to show the loader next to it while waiting for an answer)
	const lastUserMessageId = [...messages].reverse().find((m) => m.role === "user")?.id;

	const handleSendMessage = async () => {
		if (!input.trim()) return;
		if (status === "streaming" || status === "submitted") return;

		// Clear any previous error
		setSendError(null);

		try {
			const result = append({
				role: "user",
				content: input,
			});

			// append() might be sync or async, handle both cases
			if (result && typeof result.then === "function") {
				await result;
			}

			setInput("");
		} catch (error) {
			console.error("Failed to send message:", error);
			setSendError("אירעה שגיאה בשליחת ההודעה. אנא נסה שוב.");
			// Input remains intact if sending fails, allowing user to retry
		}
	};

	const handleKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
		if (event.key === "Enter" && !event.shiftKey) {
			event.preventDefault();
			handleSendMessage();
		}
	};

	// biome-ignore lint/correctness/useExhaustiveDependencies: We want to scroll to the bottom every time the answer or loading state changes.
	useEffect(() => {
		if (contentRef.current) {
			contentRef.current.scrollTop = contentRef.current.scrollHeight;
		}
	}, [messages]);
	return (
		<div data-testid="floating-chat" className={`fixed ${isDesktop ? "bottom-4 left-4" : "bottom-0 left-0 right-0 px-4 pb-4"} z-50`}>
			<Drawer direction={isDesktop ? "right" : "bottom"}>
				<DrawerTrigger asChild>
					<Button
						data-testid="chat-trigger-button"
						size="lg"
						className={`text-accent hover:bg-accent hover:text-primary rounded-full ${!isDesktop ? "w-full py-6" : ""}`}
					>
						שאל אותי על ליברפול
					</Button>
				</DrawerTrigger>
				<DrawerContent>
					<DrawerHeader dir="rtl" className="flex flex-col border-b border-slate-600">
						<DrawerTitle className="relative flex items-center justify-center sm:justify-between text-accent">
							<span data-testid="chat-title" className="mx-auto">Liver-Chat</span>
							<DrawerClose asChild>
								<Button
									variant="ghost"
									size="icon"
									aria-label="סגור"
									className="text-accent hover:bg-accent/10 absolute right-0 sm:static"
								>
									<X className="h-5 w-5" />
								</Button>
							</DrawerClose>
						</DrawerTitle>

						<DrawerDescription data-testid="chat-description" dir="rtl" className="self-start">
							ניתן לשאול כל שאלה לגבי הקבוצה, בכל שפה
						</DrawerDescription>
					</DrawerHeader>
					<div ref={contentRef} data-testid="chat-messages" className="grow px-4 overflow-y-auto text-paragraph">
						{messages.map((message) => {
							if (message.role === "assistant") {
								const dir = getDirectionFromText(message.content);
								return (
									<div key={message.id} dir={dir} className="py-2 text-sm whitespace-pre-wrap">
										<ReactMarkdown
											remarkPlugins={[remarkGfm]}
											components={{
												a: (props) => (
													<a {...props} className="underline text-accent" target="_blank" rel="noreferrer" />
												),
												code: (props) => <code {...props} className="bg-black/30 rounded px-1" />,
												pre: (props) => <pre {...props} className="bg-black/30 rounded p-2 overflow-x-auto" />,
											}}
										>
											{message.content}
										</ReactMarkdown>
									</div>
								);
							}
							if (message.role === "user") {
								const dir = getDirectionFromText(message.content);
								return (
									<div
										className="flex items-center gap-2 text-accent py-4 sticky top-0 bg-popover"
										key={message.id}
										dir={dir}
									>
										{message.content}
										{message.id === lastUserMessageId && status === "submitted" && (
											<div className="h-8 w-8">
												<Image
													className="grayscale"
													src="/liverpool-animation.gif"
													alt="liverbird"
													width={30}
													height={30}
													priority={true}
												/>
											</div>
										)}
									</div>
								);
							}
							return null;
						})}
					</div>
					{sendError && (
						<div className="px-4 py-2 text-red-500 text-sm text-center" dir="rtl">
							{sendError}
						</div>
					)}
					<div className="p-2 flex flex-row border-t">
						<Textarea
							data-testid="chat-input"
							value={input}
							onChange={(e) => {
								setInput(e.target.value);
							}}
							onKeyDown={handleKeyDown}
							placeholder="הקלד שאלה..."
							dir={inputDir}
							className={`pr-10 border-0 text-accent bg-transparent ${inputDir === "ltr" ? "text-left" : "text-right"}`}
							disabled={status === "streaming" || status === "submitted"}
						/>
						<Button
							data-testid="chat-send-button"
							size="icon"
							onClick={handleSendMessage}
							disabled={status === "streaming" || status === "submitted"}
							className="bg-transparent"
						>
							<CornerDownLeft className="h-4 w-4" color="yellow" />
						</Button>
					</div>
				</DrawerContent>
			</Drawer>
		</div>
	);
}

// src/lib/components/FloatingChat.svelte
<script lang="ts">
	import { marked } from 'marked';
	import { getDirectionFromText } from '$lib/utils';

	interface ChatMessage {
		id: string;
		role: 'user' | 'assistant';
		content: string;
	}

	let open = $state(false);
	let input = $state('');
	let messages = $state<ChatMessage[]>([]);
	let isLoading = $state(false);
	let error = $state<string | null>(null);
	let contentEl: HTMLDivElement | undefined = $state(undefined);
	let inputEl: HTMLTextAreaElement | undefined = $state(undefined);

	let inputDir = $derived(getDirectionFromText(input));

	async function sendMessage() {
		if (!input.trim() || isLoading) return;
		const currentInput = input;
		input = '';
		error = null;

		const userMsg: ChatMessage = {
			id: crypto.randomUUID(),
			role: 'user',
			content: currentInput
		};
		messages = [...messages, userMsg];

		isLoading = true;

		try {
			const response = await fetch('/api/chat', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					messages: messages.map((m) => ({
						role: m.role,
						parts: [{ type: 'text', content: m.content }]
					}))
				})
			});

			if (!response.ok) {
				throw new Error(`HTTP ${response.status}`);
			}

			const data = await response.json();
			const assistantMsg: ChatMessage = {
				id: crypto.randomUUID(),
				role: 'assistant',
				content: data.content || 'אין תשובה'
			};
			messages = [...messages, assistantMsg];
		} catch (err) {
			error = err instanceof Error ? err.message : 'שגיאה לא ידועה';
			input = currentInput;
		} finally {
			isLoading = false;
			scrollToBottom();
		}
	}

	function scrollToBottom() {
		setTimeout(() => {
			if (contentEl) {
				contentEl.scrollTop = contentEl.scrollHeight;
			}
		}, 50);
	}

	function handleKeyDown(event: KeyboardEvent) {
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			sendMessage();
		}
	}

	$effect(() => {
		if (open && inputEl) {
			setTimeout(() => inputEl?.focus(), 100);
		}
	});
</script>

<div
	data-testid="floating-chat"
	class="fixed bottom-4 left-4 z-50"
>
	{#if !open}
		<button
			data-testid="chat-trigger-button"
			class="px-6 py-3 rounded-full bg-primary text-accent border border-accent/20 hover:bg-accent hover:text-primary transition font-medium shadow-lg"
			onclick={() => (open = true)}
		>
			שאל אותי על ליברפול
		</button>
	{:else}
		<div class="w-[380px] max-h-[500px] bg-popover border border-accent/20 rounded-xl shadow-2xl flex flex-col overflow-hidden">
			<div dir="rtl" class="flex items-center justify-between border-b border-slate-600 p-3">
				<span data-testid="chat-title" class="text-accent font-bold">Liver-Chat</span>
				<button
					onclick={() => (open = false)}
					class="text-accent hover:text-accent/80 bg-transparent border-none cursor-pointer text-lg"
					aria-label="סגור"
				>
					✕
				</button>
			</div>
			<p data-testid="chat-description" dir="rtl" class="text-sm text-gray-400 px-3 py-1">
				ניתן לשאול כל שאלה לגבי הקבוצה, בכל שפה
			</p>

			<div bind:this={contentEl} data-testid="chat-messages" class="flex-1 px-4 overflow-y-auto text-paragraph min-h-[200px]">
				{#each messages as message (message.id)}
					{#if message.role === 'user'}
						{@const dir = getDirectionFromText(message.content)}
						<div class="flex items-center gap-2 text-accent py-4 sticky top-0 bg-popover" {dir}>
							{message.content}
							{#if isLoading && message === messages.filter((m) => m.role === 'user').at(-1)}
								<img class="grayscale h-8 w-8" src="/liverpool-animation.gif" alt="loading" width="30" height="30" />
							{/if}
						</div>
					{:else if message.role === 'assistant'}
						{@const dir = getDirectionFromText(message.content)}
						<div class="py-2 text-sm whitespace-pre-wrap" {dir}>
							{@html marked(message.content)}
						</div>
					{/if}
				{/each}
			</div>

			{#if error}
				<div class="text-red-500 text-sm text-center px-4 py-2" dir="rtl">
					שגיאה: {error}
					<button
						onclick={() => {
							const lastUser = messages.filter((m) => m.role === 'user').at(-1);
							if (lastUser) {
								input = lastUser.content;
								messages = messages.filter((m) => m.id !== lastUser.id);
								sendMessage();
							}
						}}
						class="text-accent hover:text-accent/80 bg-transparent border-none cursor-pointer underline ml-2"
					>
						נסה שוב
					</button>
				</div>
			{/if}

			<div class="p-2 flex flex-row border-t border-slate-600 items-center">
				<button
					data-testid="chat-send-button"
					onclick={sendMessage}
					disabled={isLoading}
					class="bg-transparent border-none cursor-pointer p-2 text-yellow-400 disabled:opacity-50"
					aria-label="שלח הודעה"
				>
					<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
						<polyline points="9 10 4 15 9 20" />
						<path d="M20 4v7a4 4 0 0 1-4 4H4" />
					</svg>
				</button>
				<textarea
					data-testid="chat-input"
					bind:this={inputEl}
					bind:value={input}
					onkeydown={handleKeyDown}
					placeholder="הקלד שאלה..."
					dir={inputDir}
					class="flex-1 border-0 text-accent bg-transparent resize-none p-2 outline-none {inputDir === 'ltr' ? 'text-left' : 'text-right'}"
					disabled={isLoading}
					rows="1"
				></textarea>
			</div>
		</div>
	{/if}
</div>
