// app/components/footer/index.tsx
import Link from "next/link";
import { InstallPrompt, PushNotificationManager } from "~/components/push-notification";

export default function Footer() {
	return (
		<div className="flex flex-wrap justify-center gap-2 py-4">
			<Link href="https://twitter.com/KapitPod">Twitter</Link>
			<span className="text-accent">|</span>
			<Link href="https://www.threads.net/@kapitpod">Threads</Link>
			<span className="text-accent">|</span>
			<Link href="https://www.facebook.com/KapitPod">Facebook</Link>
			<span className="text-accent">|</span>
			<Link href="https://www.instagram.com/kapitpod/">Instagram</Link>
			<span className="text-accent">|</span>
			<Link href="https://pod.link/1546442506">Pod.link</Link>
			<InstallPrompt />
			<span className="text-accent">|</span>
			<PushNotificationManager />
		</div>
	);
}

// src/lib/components/Footer.svelte
<div class="flex flex-wrap justify-center gap-2 py-4">
	<a href="https://twitter.com/KapitPod" target="_blank" rel="noreferrer">Twitter</a>
	<span class="text-accent">|</span>
	<a href="https://www.threads.net/@kapitpod" target="_blank" rel="noreferrer">Threads</a>
	<span class="text-accent">|</span>
	<a href="https://www.facebook.com/KapitPod" target="_blank" rel="noreferrer">Facebook</a>
	<span class="text-accent">|</span>
	<a href="https://www.instagram.com/kapitpod/" target="_blank" rel="noreferrer">Instagram</a>
	<span class="text-accent">|</span>
	<a href="https://pod.link/1546442506" target="_blank" rel="noreferrer">Pod.link</a>
</div>
